# Home Insurance EDA

This notebook contains some of the work on EDA for the home insurance dataset.

In [1]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
import random

random.seed(42)

In [2]:
df = pd.read_csv("../Data/Raw_data/home_insurance.csv")
df.head(10)

,QUOTE_DATE,COVER_START,CLAIM3YEARS,P1_EMP_STATUS,P1_PT_EMP_STATUS,BUS_USE,CLERICAL,AD_BUILDINGS,RISK_RATED_AREA_B,SUM_INSURED_BUILDINGS,...,HP3_ADDON_PRE_REN,HP3_ADDON_POST_REN,MTA_FLAG,MTA_FAP,MTA_APRP,MTA_DATE,LAST_ANN_PREM_GROSS,POL_STATUS,i,Police
0,11/22/2007,22/11/2007,N,R,NaN,N,NaN,Y,19.0,1000000.0,...,N,N,N,NaN,NaN,NaN,274.81,Lapsed,1,P000001
1,11/22/2007,01/01/2008,N,E,NaN,Y,N,Y,25.0,1000000.0,...,N,N,Y,308.83,-9.27,NaN,308.83,Live,2,P000002
2,11/23/2007,23/11/2007,N,E,NaN,N,NaN,N,NaN,0.0,...,N,N,Y,52.65,52.65,03/11/2010,52.65,Live,3,P000003
3,11/23/2007,12/12/2007,N,R,NaN,N,NaN,N,NaN,0.0,...,N,N,N,NaN,NaN,NaN,54.23,Live,4,P000004
4,11/22/2007,15/12/2007,N,R,NaN,N,NaN,Y,5.0,1000000.0,...,N,N,N,NaN,NaN,NaN,244.58,Live,5,P000005
5,11/22/2007,01/12/2007,N,R,NaN,N,NaN,N,NaN,0.0,...,N,N,N,NaN,NaN,NaN,51.45,Live,6,P000006
6,11/19/2007,12/12/2007,N,R,NaN,N,NaN,Y,1.0,1000000.0,...,N,N,Y,109.32,109.32,15/12/2008,109.32,Live,7,P000007
7,11/22/2007,01/12/2007,N,R,NaN,N,NaN,N,NaN,0.0,...,N,N,N,NaN,NaN,NaN,54.53,Cancelled,8,P000008
8,11/22/2007,01/02/2008,N,E,NaN,N,NaN,Y,0.0,1000000.0,...,N,N,Y,242.16,0.00,NaN,242.16,Live,9,P000009
9,11/22/2007,01/12/2007,N,E,NaN,N,NaN,Y,5.0,1000000.0,...,N,N,N,NaN,NaN,NaN,188.31,Live,10,P000010

In [3]:
# Use pandas profiling to quickly generate an initial report

df = df.sample(frac=0.01, random_state=1)
profile = ProfileReport(df, title="Home Insurance Data Report")
profile.to_file("home_insurance_report.html")